apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.15.3
controlPlaneEndpoint: "<virtual-ip>:6443"
etcd:
  external:
    endpoints:
      - https://<master-1-ip>:2379
      - https://<master-2-ip>:2379
      - https://<master-3-ip>:2379
    caFile: /etc/etcd/ssl/ca.pem
    certFile: /etc/etcd/ssl/client.pem
    keyFile: /etc/etcd/ssl/client-key.pem
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
apiServer:
  certSANs:
    - ${virtualIP}
    - ${master1IP}
    - ${master1Hostname}
    - ${master2IP}
    - ${master2Hostname}
    - ${master3IP}
    - ${master3Hostname}
  extraArgs:
    etcd-cafile: /etc/etcd/ssl/ca.pem
    etcd-certfile: /etc/etcd/ssl/client.pem
    etcd-keyfile: /etc/etcd/ssl/client-key.pem
  timeoutForControlPlane: 4m0s
imageRepository: k8s.gcr.io
clusterName: "test-k8s"
